language: python
env:
  - FLASK_ENV=production
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - python setup.py freeze
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  local-dir: build
  fqdn: dicomsort.com
  committer-from-gh: true
  on:
    branch: main
